### ISSUE TITLE
Not selectable input 7/8 and SDI

### ISSUE THREAD

**Issue by MartijnHeckman** [bitfocus/companion-module-barco-pds#10]
I'm new to stream deck and want to use it with a PDS902. I can't choose to select input 7,8 or sdi.
The most ports I use on a PDS 902 is 5,6,7,8 and sdi

**Comment by JeffreyDavidsz** [comment]
There is a fix for that in a later build. For now try to restart Companion when the right model is selected

**Comment by MarcHagen** [comment]
@JeffreyDavidsz bitfocus/companion#963

**Comment by JeffreyDavidsz** [comment]
Fix it merged, now I only need to update it into the core

**Comment by MarcHagen** [comment]
perfect thanks
