### ISSUE TITLE
PDS 902 missing inputs 7 and 8

### ISSUE THREAD

**Issue by nickdiacre** [bitfocus/companion-module-barco-pds#5]
Works fine with PDS 901 module, but PDS 902 is missing inputs. Tested with v2.0.0 878d7ae

**Comment by EventReplay** [comment]
**Existing Code**
	// See self.PDS_VARIANT
	if (self.config.variant >= PDS_VARIANT_901) {
		self.CHOICES_INPUTS.push({ id: 7, label: '7 DVI' })
		self.CHOICES_INPUTS.push({ id: 8, label: '8 DVI' })
	}
**Proposed Change?**
	// See self.PDS_VARIANT
	if (self.config.variant == PDS_VARIANT_901 ||
		self.config.variant == PDS_VARIANT_902) {
		self.CHOICES_INPUTS.push({ id: 7, label: '7 DVI' })
		self.CHOICES_INPUTS.push({ id: 8, label: '8 DVI' })
	}

**Comment by EventReplay** [comment]
Updated proposed change!

**Comment by JeffreyDavidsz** [comment]
Done thanks, @dogboy23 please test

**Comment by nickdiacre** [comment]
Tested with todays build - it doesn't show up yet... maybe tomorrows?

**Comment by EventReplay** [comment]
@JeffreyDavidsz 
Current Code
	// See self.PDS_VARIANT
	if (self.config.variant >= PDS_VARIANT_901 ||
		self.config.variant == PDS_VARIANT_902) {
		self.CHOICES_INPUTS.push({ id: 7, label: '7 DVI' })
		self.CHOICES_INPUTS.push({ id: 8, label: '8 DVI' })
	}

">" I think should be "="

**Comment by EventReplay** [comment]
@dogboy23 
Could you test again please.
