### ISSUE TITLE
PDS 902 missing input SDI

### ISSUE THREAD

**Issue by philz-schaad** [bitfocus/companion-module-barco-pds#8]
can't choose the SDI Input.

**Comment by MarcHagen** [comment]
Hi there!
What version of Companion are you running?

**Comment by philz-schaad** [comment]
Hi,
Version: 1.4.0

**Comment by MarcHagen** [comment]
Hi there!
So the devs of Companion have decided to put all efforts in de 2.0 release. The issue you now have is already fixed and PDS module has more features in the latest companion 2.0 dev release.
You can find that here: https://bitfocus.io/companion/download/builds/
