### ISSUE TITLE
Issue With Barco PDS Code

### ISSUE THREAD

**Issue by thunderbirdboy** [bitfocus/companion-module-barco-pds#9]
When using the Barco PDS code to try and program buttons for the input selection on all the variants it is set up for the wrong number of inputs and also is missing inputs. there should be inputs 1-4 as vga and 5-8 are dvi and there is also a SDI and black/Logo input that should be available. in the current code there are 4-vga and 2 dvi and black/logo as being available input selections.  

I have tried all the available variants. the pds701, pds901, and pds902 and all show the same issues as showing wrong input.

**Comment by josephdadams** [comment]
@thunderbirdboy transferred your issue to the PDS module.

**Comment by MarcHagen** [comment]
Hi there!
What version of Companion are you running?
In the 1.4 stable are still some issues, but bitfocus is focusing on the 2.0 release.

**Comment by thunderbirdboy** [comment]
i have both 1.4 and 2.0 and its not in the companion software its self. its
with the code for the PDS module. the coding is missing the proper inputs.

**Comment by MarcHagen** [comment]
Oké thanks for the reply.
And maybe I’m going to ask some stupid questions but better to get the easy things out of the way. 
Can you also provide me with the full version number? (So 1.4.0 (build xxxx, 2.0.0 (build xxx), these can be found in the top bar.

Have you tried to reapply the config values, checking the ip and set the correct pds variant?

Also does disabling and enabling the module fix the missing inputs?

**Comment by thunderbirdboy** [comment]
2.0 is (8c349cb)
1.4 is (backport-b402e70-1559)

now i have tried all of the things you listed as far as ip goes and trying
the different variants. but i do not have the PDS infront of me now. when i
load companion and go into the PDS module to try and program or assign
buttons no matter what i do i cannot access all the inputs to assign
buttons. the option in the PDS module just does not have them listed as
inputs. they are missing and unavailable. and its that way with all the
variants. if you look up the equipment models from barco you can see that
they are all basically the same inputs on all model variants. the
difference with all the PDS Models is on the output side.

**Comment by MarcHagen** [comment]
Prefect thanks for you reply!
I know the different pds have different inputs with the different models.
What you described is clear and should not be the case. Why this is happening is not yet clear to me and I will look into it. 

I will keep you updated

**Comment by MarcHagen** [comment]
So it seems that the config update was broken and therefore not working properly not populating the right inputs. 
I have updated the module and asked the devs if there is a possibility to get this still in 1.4 (i doubt it) 
For the 2.0 i have been working a redesign of the module with more features, this will also be available soon.

Thank for you're report :)

**Comment by thunderbirdboy** [comment]
Thank you for looking at that. We use the 902 often and I have been hoping
for use to be able to tie into the current setup and have an actual remote
control panel. I really appreciate the effort you have dedicated to this. I
will look for the update. Thank you again for keeping in touch.
